<a href="https://colab.research.google.com/github/ShaunakThakur/ML-Sem-6/blob/main/MLLab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
dataset= pd.read_csv('mammals.csv')
dataset

species   body_wt  brain_wt  non_dreaming  dreaming  \
0          Africanelephant  6654.000    5712.0           NaN       NaN   
1   Africangiantpouchedrat     1.000       6.6           6.3       2.0   
2                ArcticFox     3.385      44.5           NaN       NaN   
3     Arcticgroundsquirrel     0.920       5.7           NaN       NaN   
4            Asianelephant  2547.000    4603.0           2.1       1.8   
..                     ...       ...       ...           ...       ...   
57               Treehyrax     2.000      12.3           4.9       0.5   
58               Treeshrew     0.104       2.5          13.2       2.6   
59                  Vervet     4.190      58.0           9.7       0.6   
60            Wateropossum     3.500       3.9          12.8       6.6   
61    Yellow-belliedmarmot     4.050      17.0           NaN       NaN   

    total_sleep  life_span  gestation  predation  exposure  danger  
0           3.3       38.6      645.0          3         5       3  
1           8.3        4.5       42.0          3         1       3  
2          12.5       14.0       60.0          1         1       1  
3          16.5        NaN       25.0          5         2       3  
4           3.9       69.0      624.0          3         5       4  
..          ...        ...        ...        ...       ...     ...  
57          5.4        7.5      200.0          3         1       3  
58         15.8        2.3       46.0          3         2       2  
59         10.3       24.0      210.0          4         3       4  
60         19.4        3.0       14.0          2         1       1  
61          NaN       13.0       38.0          3         1       1  

[62 rows x 11 columns]

In [ ]:
df= pd.DataFrame(dataset)
df

species   body_wt  brain_wt  non_dreaming  dreaming  \
0          Africanelephant  6654.000    5712.0           NaN       NaN   
1   Africangiantpouchedrat     1.000       6.6           6.3       2.0   
2                ArcticFox     3.385      44.5           NaN       NaN   
3     Arcticgroundsquirrel     0.920       5.7           NaN       NaN   
4            Asianelephant  2547.000    4603.0           2.1       1.8   
..                     ...       ...       ...           ...       ...   
57               Treehyrax     2.000      12.3           4.9       0.5   
58               Treeshrew     0.104       2.5          13.2       2.6   
59                  Vervet     4.190      58.0           9.7       0.6   
60            Wateropossum     3.500       3.9          12.8       6.6   
61    Yellow-belliedmarmot     4.050      17.0           NaN       NaN   

    total_sleep  life_span  gestation  predation  exposure  danger  
0           3.3       38.6      645.0          3         5       3  
1           8.3        4.5       42.0          3         1       3  
2          12.5       14.0       60.0          1         1       1  
3          16.5        NaN       25.0          5         2       3  
4           3.9       69.0      624.0          3         5       4  
..          ...        ...        ...        ...       ...     ...  
57          5.4        7.5      200.0          3         1       3  
58         15.8        2.3       46.0          3         2       2  
59         10.3       24.0      210.0          4         3       4  
60         19.4        3.0       14.0          2         1       1  
61          NaN       13.0       38.0          3         1       1  

[62 rows x 11 columns]

In [ ]:
df=df.dropna()
df

species   body_wt  brain_wt  non_dreaming  dreaming  \
1    Africangiantpouchedrat     1.000      6.60           6.3       2.0   
4             Asianelephant  2547.000   4603.00           2.1       1.8   
5                    Baboon    10.550    179.50           9.1       0.7   
6               Bigbrownbat     0.023      0.30          15.8       3.9   
7            Braziliantapir   160.000    169.00           5.2       1.0   
8                       Cat     3.300     25.60          10.9       3.6   
9                Chimpanzee    52.160    440.00           8.3       1.4   
10               Chinchilla     0.425      6.40          11.0       1.5   
11                      Cow   465.000    423.00           3.2       0.7   
14      EasternAmericanmole     0.075      1.20           6.3       2.1   
15                  Echidna     3.000     25.00           8.6       0.0   
16         Europeanhedgehog     0.785      3.50           6.6       4.1   
17                   Galago     0.200      5.00           9.5       1.2   
21                     Goat    27.660    115.00           3.3       0.5   
22            Goldenhamster     0.120      1.00          11.0       3.4   
24                 Grayseal    85.000    325.00           4.7       1.5   
26           Groundsquirrel     0.101      4.00          10.4       3.4   
27                Guineapig     1.040      5.50           7.4       0.8   
28                    Horse   521.000    655.00           2.1       0.8   
31  Lessershort-tailedshrew     0.005      0.14           7.7       1.4   
32           Littlebrownbat     0.010      0.25          17.9       2.0   
33                      Man    62.000   1320.00           6.1       1.9   
36                    Mouse     0.023      0.40          11.9       1.3   
37                Muskshrew     0.048      0.33          10.8       2.0   
38         NAmericanopossum     1.700      6.30          13.8       5.6   
39     Nine-bandedarmadillo     3.500     10.80          14.3       3.1   
41                Owlmonkey     0.480     15.50          15.2       1.8   
42              Patasmonkey    10.000    115.00          10.0       0.9   
43               Phanlanger     1.620     11.40          11.9       1.8   
44                      Pig   192.000    180.00           6.5       1.9   
45                   Rabbit     2.500     12.10           7.5       0.9   
47                      Rat     0.280      1.90          10.6       2.6   
48                   Redfox     4.235     50.40           7.4       2.4   
49             Rhesusmonkey     6.800    179.00           8.4       1.2   
50       Rockhyrax(Heterob)     0.750     12.30           5.7       0.9   
51   Rockhyrax(Procaviahab)     3.600     21.00           4.9       0.5   
53                    Sheep    55.500    175.00           3.2       0.6   
56                   Tenrec     0.900      2.60          11.0       2.3   
57                Treehyrax     2.000     12.30           4.9       0.5   
58                Treeshrew     0.104      2.50          13.2       2.6   
59                   Vervet     4.190     58.00           9.7       0.6   
60             Wateropossum     3.500      3.90          12.8       6.6   

    total_sleep  life_span  gestation  predation  exposure  danger  
1           8.3        4.5       42.0          3         1       3  
4           3.9       69.0      624.0          3         5       4  
5           9.8       27.0      180.0          4         4       4  
6          19.7       19.0       35.0          1         1       1  
7           6.2       30.4      392.0          4         5       4  
8          14.5       28.0       63.0          1         2       1  
9           9.7       50.0      230.0          1         1       1  
10         12.5        7.0      112.0          5         4       4  
11          3.9       30.0      281.0          5         5       5  
14          8.4        3.5       42.0          1         1       1  
15          8.6       50.0       28

In [ ]:
X= df.iloc[:, 1:-1].values
y= df.iloc[:, -1].values

In [ ]:
X

array([[1.000e+00, 6.600e+00, 6.300e+00, 2.000e+00, 8.300e+00, 4.500e+00,
        4.200e+01, 3.000e+00, 1.000e+00],
       [2.547e+03, 4.603e+03, 2.100e+00, 1.800e+00, 3.900e+00, 6.900e+01,
        6.240e+02, 3.000e+00, 5.000e+00],
       [1.055e+01, 1.795e+02, 9.100e+00, 7.000e-01, 9.800e+00, 2.700e+01,
        1.800e+02, 4.000e+00, 4.000e+00],
       [2.300e-02, 3.000e-01, 1.580e+01, 3.900e+00, 1.970e+01, 1.900e+01,
        3.500e+01, 1.000e+00, 1.000e+00],
       [1.600e+02, 1.690e+02, 5.200e+00, 1.000e+00, 6.200e+00, 3.040e+01,
        3.920e+02, 4.000e+00, 5.000e+00],
       [3.300e+00, 2.560e+01, 1.090e+01, 3.600e+00, 1.450e+01, 2.800e+01,
        6.300e+01, 1.000e+00, 2.000e+00],
       [5.216e+01, 4.400e+02, 8.300e+00, 1.400e+00, 9.700e+00, 5.000e+01,
        2.300e+02, 1.000e+00, 1.000e+00],
       [4.250e-01, 6.400e+00, 1.100e+01, 1.500e+00, 1.250e+01, 7.000e+00,
        1.120e+02, 5.000e+00, 4.000e+00],
       [4.650e+02, 4.230e+02, 3.200e+00, 7.000e-01, 3.900e+00, 3.000e+01

In [ ]:
y

array([3, 4, 4, 1, 4, 1, 1, 4, 5, 1, 2, 2, 2, 5, 2, 1, 3, 4, 5, 4, 1, 1,
       3, 3, 1, 1, 2, 4, 2, 4, 5, 3, 1, 2, 2, 3, 5, 2, 3, 2, 4, 1])

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [ ]:
X_train

array([[2.300e-02, 4.000e-01, 1.190e+01, 1.300e+00, 1.320e+01, 3.200e+00,
        1.900e+01, 4.000e+00, 1.000e+00],
       [6.200e+01, 1.320e+03, 6.100e+00, 1.900e+00, 8.000e+00, 1.000e+02,
        2.670e+02, 1.000e+00, 1.000e+00],
       [6.800e+00, 1.790e+02, 8.400e+00, 1.200e+00, 9.600e+00, 2.900e+01,
        1.640e+02, 2.000e+00, 3.000e+00],
       [1.000e+01, 1.150e+02, 1.000e+01, 9.000e-01, 1.090e+01, 2.020e+01,
        1.700e+02, 4.000e+00, 4.000e+00],
       [7.500e-01, 1.230e+01, 5.700e+00, 9.000e-01, 6.600e+00, 7.000e+00,
        2.250e+02, 2.000e+00, 2.000e+00],
       [2.500e+00, 1.210e+01, 7.500e+00, 9.000e-01, 8.400e+00, 1.800e+01,
        3.100e+01, 5.000e+00, 5.000e+00],
       [4.235e+00, 5.040e+01, 7.400e+00, 2.400e+00, 9.800e+00, 9.800e+00,
        5.200e+01, 1.000e+00, 1.000e+00],
       [2.000e+00, 1.230e+01, 4.900e+00, 5.000e-01, 5.400e+00, 7.500e+00,
        2.000e+02, 3.000e+00, 1.000e+00],
       [1.600e+02, 1.690e+02, 5.200e+00, 1.000e+00, 6.200e+00, 3.040e+01

In [ ]:
X_test

array([[2.300e-02, 3.000e-01, 1.580e+01, 3.900e+00, 1.970e+01, 1.900e+01,
        3.500e+01, 1.000e+00, 1.000e+00],
       [1.055e+01, 1.795e+02, 9.100e+00, 7.000e-01, 9.800e+00, 2.700e+01,
        1.800e+02, 4.000e+00, 4.000e+00],
       [4.800e-02, 3.300e-01, 1.080e+01, 2.000e+00, 1.280e+01, 2.000e+00,
        3.000e+01, 4.000e+00, 1.000e+00],
       [1.040e-01, 2.500e+00, 1.320e+01, 2.600e+00, 1.580e+01, 2.300e+00,
        4.600e+01, 3.000e+00, 2.000e+00],
       [1.040e+00, 5.500e+00, 7.400e+00, 8.000e-01, 8.200e+00, 7.600e+00,
        6.800e+01, 5.000e+00, 3.000e+00],
       [1.920e+02, 1.800e+02, 6.500e+00, 1.900e+00, 8.400e+00, 2.700e+01,
        1.150e+02, 4.000e+00, 4.000e+00],
       [5.000e-03, 1.400e-01, 7.700e+00, 1.400e+00, 9.100e+00, 2.600e+00,
        2.150e+01, 5.000e+00, 2.000e+00],
       [3.600e+00, 2.100e+01, 4.900e+00, 5.000e-01, 5.400e+00, 6.000e+00,
        2.250e+02, 3.000e+00, 2.000e+00],
       [2.800e-01, 1.900e+00, 1.060e+01, 2.600e+00, 1.320e+01, 4.700e+00

In [ ]:
y_train

array([3, 1, 2, 4, 2, 5, 1, 3, 4, 2, 2, 1, 1, 2, 5, 1, 5, 1, 1, 2, 5, 4,
       4, 4, 3, 3, 1, 1, 2, 1, 5, 2, 2])

In [ ]:
y_test

array([1, 4, 3, 2, 4, 4, 4, 3, 3])

In [ ]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [ ]:
y_pred= regressor.predict(X_test)
y_pred

array([0.54268759, 3.85180606, 3.1009086 , 2.46258394, 4.47723622,
       3.80547503, 4.19446632, 2.92895438, 2.33260252])

In [ ]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
score= r2_score(y_test, y_pred)
score

0.863971644883408

In [ ]:
score1=mean_absolute_error(y_test, y_pred)
score1

0.3081854999696534

In [ ]:
score2= mean_squared_error(y_test, y_pred)
score2

0.13434899270774509